### PR TITLE
Issue 4 command line power

### PR DESCRIPTION
**Pull request by hrford**
Points 1 to 3 in issue #4

### CODE REVIEW

**Comment by hrford** [comment]
Example output:
Solar voltage: 14.07V
Solar current: 0.94A
Solar power: 13.93W
Load voltage: 13.27V
Load current: 0A
Load power: 0.0W
Battery voltage: 13.27V
Battery current: 1.03A
Battery power: 13.8W
Battery state of charge: 87%
Battery temperature: 20.89°C
Remote battery temperature: 0°C
Controller temperature: 23.01°C
...

**Review by rosswarren — APPROVED** [review]
This looks great, thanks for the contribution!

**Comment by rosswarren** [comment]
I'll assume this works because you pasted the output, I don't have my charge controller with me right now.

**Comment by hrford** [comment]
This ticket can be closed.

**Pull request merged**
